import HtmlWebpackPlugin from 'html-webpack-plugin'
import ExtractTextPlugin from 'extract-text-webpack-plugin'
import path from 'path'

import htmlMinifyOpts from './html-minifier'

const rootDir = path.resolve(__dirname, '../..')

export default ({
  mode,
  entry = {
    app: [ path.join(rootDir, 'app/index.js') ]
  },
  plugins = [],
  rules = [],
  resolve = {}
}) => {
  return {
    mode,
    entry: { ...entry },
    output: {
      path: path.join(rootDir, 'build/assets'),
      publicPath: '/assets/',
      filename: 'js/[name].[hash:5].js'
    },
    plugins: [
      new HtmlWebpackPlugin({
        inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
        template: path.join(rootDir, 'assets/html/index.html'),
        filename: path.join(rootDir, 'build/index.html'),
        minify: htmlMinifyOpts
      }),
      new ExtractTextPlugin('css/[name].[hash:5].css'),
      ...plugins
    ],
    module: {
      rules: [
        {
          test: /\.jsx?$/,
          exclude: /node_modules/,
          use: [
            {
              loader: 'babel-loader',
              options: {
                presets: [
                  [ 'env', {
                    target: {
                      browser: [ 'last 2 versions', 'safari >= 7' ]
                    }
                  } ],
                  'react',
                  'stage-2'
                ],
                plugins: [
                  'transform-decorators-legacy',
                  'transform-runtime'
                ]
              }
            }
          ]
        },
        {
          test: /\.(jpg|png|gif|svg)$/,
          use: [
            {
              loader: 'file-loader',
              options: {
                name: 'img/[name].[hash:5].[ext]',
                publicPath: '/assets/',
                emitFile: true
              }
            }
          ]
        },
        {
          test: /\.(ttf|eot|woff|woff2)$/,
          use: [
            {
              loader: 'file-loader',
              options: {
                name: 'fonts/[name].[hash:5].[ext]',
                publicPath: '/assets/',
                emitFile: true
              }
            }
          ]
        },
        {
          test: /.styl$/,
          use: ExtractTextPlugin.extract({
            fallback: 'style-loader',
            use: ['css-loader', 'stylus-loader']
          })
        },
        ...rules
      ]
    },
    resolve: {
      modules: [ 'app', 'node_modules', 'assets' ],
      extensions: [ '.js', '.jsx', '.styl' ],
      ...resolve
    }
  }
}
