const HtmlWebpackPlugin = require('html-webpack-plugin');
const path = require('path');

const rootDir = path.resolve(__dirname, '../..');

module.exports = {
  entry: {
    app: [ path.join(rootDir, 'app/app.js') ]
  },
  output: {
    path: path.join(rootDir, 'build'),
    publicPath: '/assets',
    filename: '[name].bundle.js'
  },
  plugins: [
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: path.join(rootDir, 'app/index.html'),
    })
  ]
};
